### ISSUE TITLE
Laravel 6 - Error with 1.9.5. version

### ISSUE THREAD

**Issue by pixelzdesign** [albertcht/invisible-recaptcha#147]
When update package from 1.9.4. to 1.9.5. in Laravel 6 I got error:

```
Too few arguments to function AlbertCht\InvisibleReCaptcha\InvisibleReCaptchaServiceProvider::
         AlbertCht\InvisibleReCaptcha\{closure}(), 1 passed and exactly 2 expected
```
This part of the code is making an error (in new version is added $nonce):
```
$blade->directive('captchaScripts', function ($lang, $nonce) {
            return "<?php echo app('captcha')->renderFooterJS({$lang}, {$nonce}); ?>";
});
```

**Comment by albertcht** [comment]
Hi @pixelzdesign ,

It's been fixed in release `v1.9.5`
